include_HEADERS = src/union_util.h 

src_libunion_la_SOURCES = src/union_util.c	\
                        src/benchmarks/conc-latency.c \
                        src/benchmarks/conc-cosmoflow.c \
			src/benchmarks/jacobi3d.C

dist_data_DATA = src/benchmarks/conceptual.json


				
